# 로지스틱 회귀 

### 이진 클래스 분류기 훈련하기

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data[:100,:]
target = iris.target[:100]

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state = 0)

model = logistic_regression.fit(features_standardized,target)

In [2]:
new_observation = [[.5,.5,.5,.5]]

model.predict(new_observation)

array([1])

In [3]:
model.predict_proba(new_observation)

array([[0.17738424, 0.82261576]])

### 다중 클래스 분류기 훈련하기

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data
target = iris.target

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state = 0, multi_class = 'ovr')

model = logistic_regression.fit(features_standardized, target)

### 규제로 분산 줄이기

In [7]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data
target = iris.target

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegressionCV(penalty = 'l2',Cs = 10,random_state = 0,n_jobs = -1)

model = logistic_regression.fit(features_standardized,target)

In [8]:
logistic_regression.C_

array([21.5443469, 21.5443469, 21.5443469])

### 대용량 데이터에서 분류기 훈련하기

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data
target = iris.target

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state = 0, solver = 'sag')

model = logistic_regression.fit(features_standardized, target)

### 불균형한 클래스 다루기

In [10]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
features = iris.data
target = iris.target

features = features[40:,:]
target = target[40:]

target = np.where((target ==0), 0 , 1)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

logistic_regression = LogisticRegression(random_state = 0, class_weight = 'balanced')

model = logistic_regression.fit(features_standardized, target)

In [11]:
from sklearn.utils.class_weight import compute_class_weight

compute_class_weight('balanced',[0,1],target)

C:\Users\jlee0\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass classes=[0, 1], y=[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


array([5.5 , 0.55])

In [13]:
logistic_regression = LogisticRegression(random_state = 0, class_weight = {0:10,1:1})

model = logistic_regression.fit(features_standardized,target)