# 나이브 베이즈

### 연속적인 특성으로 분류기 훈련하기

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
features = iris.data
target = iris.target

classifier = GaussianNB()

model = classifier.fit(features,target)

In [2]:
new_observation = [[4,4,4,0.4]]
model.predict(new_observation)

array([1])

### 이산적인 카운트 특성으로 분류기 훈련하기 (이산 : 연속되지 않음)

In [4]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

text_data = np.array(['I love Brazil. Brazil!','Brazil is best','Germany beats both'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

features = bag_of_words.toarray()

target = np.array([0,0,1])

classifier = MultinomialNB(class_prior = [0.25,0.5])

model = classifier.fit(features,target)

In [5]:
new_observation = [[0,0,0,1,0,1,0]]

model.predict(new_observation)

array([0])

### 이진 특성으로 나이브 베이즈 분류기 훈련하기

In [7]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

features = np.random.randint(2, size = (100,3))

target = np.random.randint(2,size=(100,1)).ravel()

classifier = BernoulliNB(class_prior = [0.25,0.5])

model = classifier.fit(features,target)

### 예측 확률 보정하기

In [8]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV

iris = datasets.load_iris()
features = iris.data
target = iris.target

classifier = GaussianNB()

classifier_sigmoid = CalibratedClassifierCV(classifier, cv = 2, method = 'sigmoid')

classifier_sigmoid.fit(features,target)

new_observation = [[2.6,2.6,2.6,0.4]]

classifier_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])