# 벡터 만들기

In [12]:
import numpy as np

In [2]:
vector_row = np.array([1,2,3])

In [3]:
vector_row

array([1, 2, 3])

In [5]:
vector_columns = np.array([[1],[2],[3]])

In [6]:
vector_columns

array([[1],
       [2],
       [3]])

# 행렬 만들기

In [7]:
empty_matrix = np.empty((3,2))  #크기가 (3,2)인 빈 행렬을 만드는 것

In [8]:
zero_matrix = np.zeros((3,2))  #크기가 (3,2)이고 0으로 채워진 행렬을 만드는 것

In [9]:
one_matrix = np.ones((3,2))  #크기가 (3,2)이고 1로 채워진 행렬을 만드는 것

In [11]:
seven_matrix = np.zeros((3,2)) + 7

seven_matrix = np.full((3,2),7)  #위의 seven_matrix 결과와 같다. 첫번째 매개변수에는 배열의 크기, 두번째에는 채울 값을 전달한다.

# 희소 행렬 만들기

0이 아닌 데이터가 매우 적을 때 이를 효율적으로 표현

In [13]:
from scipy import sparse

matrix = np.array([[0,0],[0,1],[3,0]])

matrix_sparse = sparse.csr_matrix(matrix)

In [14]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [16]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[3,0,0,0,0,0,0,0,0,0]])

In [17]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [18]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [19]:
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])),shape = (3,10))

print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [20]:
print(matrix_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [21]:
matrix_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

# 원소 선택하기

In [22]:
vector = np.array([1,2,3,4,5,6])

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
vector[2]

3

In [24]:
matrix[1,1]

5

In [25]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [26]:
vector[:3]

array([1, 2, 3])

In [27]:
vector[-1]

6

In [28]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [32]:
matrix[[0,2]]  #팬시 인덱싱 : 행과 열의 인덱스를 적어 배열을 선탱

array([[1, 2, 3],
       [7, 8, 9]])

In [33]:
matrix[[0,2],[1,0]]

array([2, 7])

In [34]:
#불리언 마스크

mask = matrix > 5

matrix[mask]

array([6, 7, 8, 9])

# 행렬 정보 확인하기

In [35]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix.shape

(3, 4)

In [36]:
matrix.size

12

In [37]:
matrix.ndim

2

In [38]:
matrix.dtype

dtype('int32')

In [39]:
matrix.itemsize

4

In [40]:
matrix.nbytes

48

# 벡터화 연산 적용하기

In [42]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

add_100 = lambda i : i + 100

vectorized_add_100 = np.vectorize(add_100)

vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [43]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [44]:
matrix + [100,100,100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [45]:
matrix + [[100],[200],[300]]

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

# 최댓값, 최솟값 찾기

In [46]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.max(matrix)

9

In [47]:
np.min(matrix)

1

In [48]:
np.max(matrix,axis = 0)

array([7, 8, 9])

In [49]:
np.max(matrix,axis = 1)

array([3, 6, 9])

In [50]:
vector_column = np.max(matrix,axis = 1,keepdims = True)

In [51]:
vector_column

array([[3],
       [6],
       [9]])

In [52]:
matrix - vector_column

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

# 평균 분산, 표준편차 계산하기

In [53]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
np.mean(matrix)

5.0

In [55]:
np.var(matrix)

6.666666666666667

In [56]:
np.std(matrix)

2.581988897471611

In [57]:
np.mean(matrix, axis = 0)

array([4., 5., 6.])

In [59]:
#모집단에서 추출한 샘플의 자유도를 고려하여 편향되지 않은 분산과 표준편차를 계산. 
#ddof = 1로 지정하여 추정값을 얻는다

np.std(matrix,ddof = 1)

#판다스 데이터프레임의  std메서드는 ddof의 기본값이 1이다.

2.7386127875258306

In [60]:
import pandas as pd

df = pd.DataFrame(matrix.flatten())
df.std()

0    2.738613
dtype: float64

In [61]:
# 실제로 머신러닝을 훈련할때 자유도가 큰 영향을 미치지 않음. 그래서 고려 x

# 배열 크기 바꾸기

In [62]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [63]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
matrix.size

12

In [66]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [69]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 벡터나 행렬 전치하기

In [71]:
matrix = np.array([[1,4,7],[2,5,8],[3,6,9]])

In [72]:
matrix.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 행렬 펼치기

In [73]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape : 넘파이 배열의 뷰를 반환
    
- flatten : 새로운 배열을 만듬

# 행렬의 랭크 구하기

In [76]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])

np.linalg.matrix_rank(matrix)

2

# 행렬식 계산하기

In [78]:
matrix = np.array([[1,2,3],[2,3,3],[4,4,9]])

np.linalg.det(matrix)

-8.999999999999998

# 행렬의 대각원소 추출하기

In [79]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

matrix.diagonal()

array([1, 4, 9])

In [80]:
matrix.diagonal(offset=1)

array([2, 6])

In [82]:
matrix.diagonal(offset=-1)

array([2, 8])

# 행렬의 대각합 계산하기

In [83]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

matrix.trace()

14

# 고윳값과 고유벡터 찾기

In [84]:
matrix = np.array([[1,-1,3],[1,1,6],[3,8,9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [85]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [86]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# 점곱 계산하기

In [87]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a,vector_b)

32

In [88]:
vector_a @ vector_b

32

# 행렬의 덧셈과 뺄셈

In [89]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])

In [90]:
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [91]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# 행렬 곱셈

In [93]:
matrix_a = np.array([[1,1],[1,2]])
matrix_b = np.array([[1,3],[1,2]])

In [94]:
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [95]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# 역행렬

In [96]:
matrix = np.array([[1,4],[2,5]])

In [97]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [98]:
np.linalg.pinv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# 난수 생성하기

In [99]:
np.random.seed(0)

np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [100]:
np.random.randint(0,11,3)

array([3, 7, 9])

In [101]:
np.random.normal(0.0,1.0,3)

array([-1.42232584,  1.52006949, -0.29139398])

In [102]:
np.random.logistic(0.0,1.0,3)

array([-0.98118713, -0.08939902,  1.46416405])

In [103]:
np.random.uniform(1.0,2.0,3)

array([1.47997717, 1.3927848 , 1.83607876])

In [104]:
np.random.rand(2,4)

array([[0.33739616, 0.64817187, 0.36824154, 0.95715516],
       [0.14035078, 0.87008726, 0.47360805, 0.80091075]])

In [106]:
np.random.randint(0,3,10)

array([1, 2, 0, 1, 1, 1, 0, 2, 0, 2])

In [107]:
np.random.standard_normal((2,3))

array([[-0.13309028, -0.24214951,  1.51439128],
       [-0.3330574 ,  0.04736482,  1.46274045]])

In [108]:
np.random.randn(2,3)

array([[ 1.53502913,  0.56644004,  0.14926509],
       [-1.078278  ,  1.39547227,  1.78748405]])

In [109]:
np.random.choice([0,1,2],5)

array([1, 1, 2, 2, 2])

In [110]:
a = np.array([0,1,2,3,4])

np.random.shuffle(a)

In [111]:
a

array([4, 1, 2, 0, 3])

In [113]:
np.random.permutation(a)

array([0, 4, 2, 1, 3])

In [114]:
np.random.permutation(10)

array([1, 2, 5, 0, 8, 3, 7, 9, 6, 4])