In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt

Instructions for updating:
non-resource variables are not supported in the long term


In [14]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.] 

In [15]:
X1 = tf.placeholder(tf.float32)
X2 = tf.placeholder(tf.float32)
X3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [16]:
W1 = tf.Variable(tf.random_normal([1]),name = 'weight1')
W2 = tf.Variable(tf.random_normal([1]),name = 'weight2')
W3 = tf.Variable(tf.random_normal([1]),name = 'weight3')
b = tf.Variable(tf.random_normal([1]),name = 'bias')
hypothesis = X1 * W1 + X2 * W2 + X3 * W3 + b

In [17]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [19]:
for step in range(2001) : 
    cost_val, hy_val, k = sess.run([cost,hypothesis,train],feed_dict={X1 : x1_data, X2 : x2_data, X3 : x3_data, Y : y_data})
    if step%10 == 0 : 
        print(step,"cost : ",cost_val, "\n prediction : \n",hy_val)

0 cost :  2391.5737 
 prediction : 
 [197.9658  234.87282 233.15912 250.6166  181.35545]
10 cost :  3.4000072 
 prediction : 
 [154.72984 182.91689 181.96056 194.86389 141.72778]
20 cost :  3.3674119 
 prediction : 
 [154.59349 182.76344 181.8039  194.69449 141.61234]
30 cost :  3.3567395 
 prediction : 
 [154.58755 182.76671 181.80165 194.69325 141.61642]
40 cost :  3.346098 
 prediction : 
 [154.58202 182.77045 181.79987 194.69252 141.62085]
50 cost :  3.3355103 
 prediction : 
 [154.57648 182.77417 181.7981  194.69179 141.62526]
60 cost :  3.3249958 
 prediction : 
 [154.57098 182.7779  181.79637 194.69112 141.62968]
70 cost :  3.3145218 
 prediction : 
 [154.56548 182.78159 181.79459 194.69037 141.63406]
80 cost :  3.3041012 
 prediction : 
 [154.56001 182.7853  181.79282 194.68965 141.63846]
90 cost :  3.2937496 
 prediction : 
 [154.55455 182.78899 181.79109 194.68895 141.64282]
100 cost :  3.2834365 
 prediction : 
 [154.54912 182.79268 181.78935 194.68826 141.64719]
110 cost : 