In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt

In [3]:
X_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
Y_data = [[152.],[185.],[180.],[196.],[142.]]

In [4]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [5]:
W = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [7]:
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001) : 
    cost_val, hy_val, k = sess.run([cost,hypothesis,train],feed_dict={X: X_data, Y : Y_data})
    if step%10 == 0 : 
        print(step,"cost : ",cost_val, "\n prediction : \n",hy_val)

0 cost :  862.24866 
 prediction : 
 [[181.6579 ]
 [213.0696 ]
 [213.10347]
 [229.21257]
 [163.09113]]
10 cost :  7.2634187 
 prediction : 
 [[155.78188]
 [181.98767]
 [182.46794]
 [195.85272]
 [139.38696]]
20 cost :  7.219878 
 prediction : 
 [[155.69351]
 [181.90051]
 [182.37213]
 [195.74983]
 [139.324  ]]
30 cost :  7.18432 
 prediction : 
 [[155.6832 ]
 [181.9071 ]
 [182.3687 ]
 [195.74757]
 [139.33257]]
40 cost :  7.149007 
 prediction : 
 [[155.67314]
 [181.91397]
 [182.3656 ]
 [195.74564]
 [139.3413 ]]
50 cost :  7.113818 
 prediction : 
 [[155.6631 ]
 [181.9208 ]
 [182.36247]
 [195.7437 ]
 [139.35002]]
60 cost :  7.0788894 
 prediction : 
 [[155.6531 ]
 [181.92763]
 [182.35938]
 [195.74176]
 [139.3587 ]]
70 cost :  7.0440927 
 prediction : 
 [[155.64313]
 [181.93443]
 [182.35628]
 [195.73984]
 [139.36739]]
80 cost :  7.0094786 
 prediction : 
 [[155.63316]
 [181.94122]
 [182.35318]
 [195.73792]
 [139.37602]]
90 cost :  6.975096 
 prediction : 
 [[155.62328]
 [181.94801]
 [182.3