In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt
import numpy as np
tf.set_random_seed(777)

In [8]:
xy = np.loadtxt('data-01-test-score.csv',delimiter = ',', dtype = np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [9]:
print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data,len(y_data))

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 6


In [10]:
X = tf.placeholder(tf.float32,shape = [None,3])
Y = tf.placeholder(tf.float32,shape = [None,1])

W = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [11]:
hypothesis = tf.matmul(X,W) +b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [18]:
for step in range(2001) : 
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],feed_dict = {X : x_data, Y : y_data})

    if step % 10 ==0 : 
        print(step,"cost :",cost_val,"\nprediction :\n",hy_val)

0 cost : 1.2986499 
prediction :
 [[152.98862]
 [183.913  ]
 [181.41078]
 [194.39383]
 [142.9917 ]
 [100.71822]]
10 cost : 1.2976266 
prediction :
 [[152.98705]
 [183.91365]
 [181.41008]
 [194.39375]
 [142.99226]
 [100.71999]]
20 cost : 1.2966205 
prediction :
 [[152.98552]
 [183.91432]
 [181.4094 ]
 [194.39369]
 [142.99284]
 [100.72175]]
30 cost : 1.2955991 
prediction :
 [[152.98398]
 [183.91498]
 [181.40869]
 [194.39363]
 [142.9934 ]
 [100.72351]]
40 cost : 1.294569 
prediction :
 [[152.98242]
 [183.91563]
 [181.40796]
 [194.39354]
 [142.99391]
 [100.72525]]
50 cost : 1.2935888 
prediction :
 [[152.98091 ]
 [183.91628 ]
 [181.40727 ]
 [194.39346 ]
 [142.99448 ]
 [100.727005]]
60 cost : 1.2925854 
prediction :
 [[152.97937]
 [183.91692]
 [181.40659]
 [194.39339]
 [142.995  ]
 [100.72876]]
70 cost : 1.2915816 
prediction :
 [[152.97786]
 [183.91757]
 [181.40587]
 [194.39331]
 [142.99553]
 [100.73049]]
80 cost : 1.2905847 
prediction :
 [[152.97633]
 [183.91821]
 [181.40517]
 [194.3932

In [19]:
print("YOUR SCORE WILL BE ",sess.run(hypothesis,feed_dict = {X : [[100,70,101]]}))

YOUR SCORE WILL BE  [[177.39714]]


In [20]:
print("OTHER SCORES WILL BE ",sess.run(hypothesis,feed_dict = {X : [[60,70,110],[90,100,80]]}))

OTHER SCORES WILL BE  [[112.55096]
 [193.60884]]
