In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt
import numpy as np

In [3]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'],shuffle = False, name = 'filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [4]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [5]:
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value,record_defaults = record_defaults)

In [6]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1],xy[-1:]],batch_size = 10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [7]:
X = tf.placeholder(tf.float32,shape = [None ,3])
Y = tf.placeholder(tf.float32,shape = [None, 1])
W = tf.Variable(tf.random_normal([3, 1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [8]:
hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [16]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.0000001)
train = optimizer.minimize(cost)

In [17]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

In [18]:
for step in range(2001) : 
    x_batch, y_batch = sess.run([train_x_batch,train_y_batch])
    cost_val,hy_val,_ = sess.run([cost,hypothesis,train],feed_dict = {X : x_batch, Y : y_batch})
    
    if step%10==0 : 
        print(step,"cost :",cost_val,"\n prediction \n",hy_val)
coord.request_stop()
coord.join(threads)

0 cost : 353.35257 
 prediction 
 [[168.8679 ]
 [205.56299]
 [201.70479]
 [214.71408]
 [161.30699]
 [111.16912]
 [168.8679 ]
 [205.56299]
 [201.70479]
 [214.71408]]
10 cost : 295.1535 
 prediction 
 [[160.69922]
 [110.7211 ]
 [168.20518]
 [204.7662 ]
 [200.91983]
 [213.85925]
 [160.69922]
 [110.7211 ]
 [168.20518]
 [204.7662 ]]
20 cost : 282.9008 
 prediction 
 [[200.17496]
 [213.04807]
 [160.12244]
 [110.29589]
 [167.57632]
 [204.01007]
 [200.17496]
 [213.04807]
 [160.12244]
 [110.29589]]
30 cost : 279.00912 
 prediction 
 [[166.96907]
 [203.27997]
 [199.45569]
 [212.2648 ]
 [159.56549]
 [109.88532]
 [166.96907]
 [203.27997]
 [199.45569]
 [212.2648 ]]
40 cost : 234.72408 
 prediction 
 [[159.02554 ]
 [109.487274]
 [166.38028 ]
 [202.57211 ]
 [198.75833 ]
 [211.50537 ]
 [159.02554 ]
 [109.487274]
 [166.38028 ]
 [202.57211 ]]
50 cost : 224.56429 
 prediction 
 [[198.09634]
 [210.78444]
 [158.51297]
 [109.10941]
 [165.82143]
 [201.90015]
 [198.09634]
 [210.78444]
 [158.51297]
 [109.10941

In [19]:
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[178.16655]]
Other scores will be  [[ 78.22907]
 [201.3776 ]]
