In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [3]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [6]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [7]:
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val,W_val,_= sess.run([cost,W,optimizer],feed_dict={X:x_data, Y : y_data})
        print(step,cost_val,W_val)
    print("prediction:",sess.run(prediction,feed_dict = {X : x_test}))
    print("Accuracy:",sess.run(accuracy,feed_dict = {X : x_test, Y: y_test}))

0 7.671439 [[ 1.2324796  -1.4188482  -0.06741901]
 [ 0.31392008  0.89494157  0.01157486]
 [ 0.9974763  -1.0172207   1.2635636 ]]
1 5.5284777 [[ 1.1854682e+00 -1.3813694e+00 -5.7886377e-02]
 [ 1.5151711e-01  1.0698943e+00 -9.7486377e-04]
 [ 8.4709972e-01 -8.2974684e-01  1.2264663e+00]]
2 4.493195 [[ 1.1672682  -1.3439425  -0.07711315]
 [ 0.13535269  1.2447034  -0.15961957]
 [ 0.8421759  -0.64236236  1.0440056 ]]
3 3.4769049 [[ 1.1178472  -1.3067296  -0.06490514]
 [-0.03952679  1.4185697  -0.15860637]
 [ 0.67727804 -0.45565194  1.0221932 ]]
4 2.4784508 [[ 1.1039907  -1.2730694  -0.08470874]
 [-0.03333121  1.5702525  -0.3164848 ]
 [ 0.690511   -0.2856372   0.8389455 ]]
5 1.8322272 [[ 1.0693895  -1.2551907  -0.06798625]
 [-0.11195891  1.621291   -0.2888956 ]
 [ 0.6027285  -0.20108697  0.8421778 ]]
6 1.7379774 [[ 1.0587804  -1.25244    -0.06012791]
 [-0.07087543  1.5812635  -0.28995153]
 [ 0.6371372  -0.20262432  0.8093065 ]]
7 1.7010417 [[ 1.0394158  -1.2451494  -0.04805391]
 [-0.07082636 