In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt
import numpy as np

In [22]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = min_max_scaler(xy) #정의하고 사용해야 하는듯 하다
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data, y_data)

[[0.99999999 0.99999999 0.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782]
 [0.54412549 0.50274824 0.57608696 0.606468  ]
 [0.33890353 0.31368023 0.10869565 0.45989134]
 [0.51436    0.42582389 0.30434783 0.58504805]
 [0.49556179 0.42582389 0.31521739 0.48131134]
 [0.11436064 0.         0.20652174 0.22007776]
 [0.         0.07747099 0.5326087  0.        ]] [[1.        ]
 [0.83755791]
 [0.6606331 ]
 [0.43800918]
 [0.42624401]
 [0.49276137]
 [0.18597238]
 [0.        ]]


In [23]:
X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,1])
W = tf.Variable(tf.random_normal([4,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [24]:
hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val,hy_val,_= sess.run([cost,hypothesis,train],feed_dict={X:x_data, Y : y_data})
        print(step,"Cost:",cost_val,"\nprediction:\n",hy_val)

0 Cost: 4.5118937 
prediction:
 [[-2.3063202 ]
 [-1.7944479 ]
 [-1.6089983 ]
 [-1.3829701 ]
 [-1.5761765 ]
 [-1.4671228 ]
 [-0.98766077]
 [-0.7351893 ]]
1 Cost: 4.5115547 
prediction:
 [[-2.3062115]
 [-1.7943442]
 [-1.6089118]
 [-1.3829029]
 [-1.576097 ]
 [-1.4670459]
 [-0.9876099]
 [-0.7351399]]
2 Cost: 4.5112157 
prediction:
 [[-2.306103 ]
 [-1.7942405]
 [-1.6088252]
 [-1.3828359]
 [-1.5760174]
 [-1.4669693]
 [-0.9875591]
 [-0.7350905]]
3 Cost: 4.5108767 
prediction:
 [[-2.3059943 ]
 [-1.7941369 ]
 [-1.6087387 ]
 [-1.3827686 ]
 [-1.5759379 ]
 [-1.4668925 ]
 [-0.98750824]
 [-0.7350411 ]]
4 Cost: 4.5105376 
prediction:
 [[-2.3058858 ]
 [-1.7940333 ]
 [-1.6086521 ]
 [-1.3827015 ]
 [-1.5758582 ]
 [-1.4668157 ]
 [-0.9874574 ]
 [-0.73499167]]
5 Cost: 4.5101986 
prediction:
 [[-2.305777  ]
 [-1.7939296 ]
 [-1.6085657 ]
 [-1.3826344 ]
 [-1.5757787 ]
 [-1.4667389 ]
 [-0.98740655]
 [-0.73494226]]
6 Cost: 4.5098596 
prediction:
 [[-2.3056684 ]
 [-1.7938259 ]
 [-1.6084793 ]
 [-1.3825673 ]
 [-1.5