In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [4]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [9]:
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val,W_val,_= sess.run([cost,W,optimizer],feed_dict={X:x_data, Y : y_data})
        print(step,cost_val,W_val)
    print("prediction:",sess.run(prediction,feed_dict = {X : x_test}))
    print("Accuracy:",sess.run(accuracy,feed_dict = {X : x_test, Y: y_test}))

0 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
1 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
2 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
3 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
4 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
5 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
6 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.0432003  -0.14811096  0.00284993]]
7 5.544712 [[-1.0424588   0.49087077  0.65708673]
 [ 1.1685685  -0.06989745 -0.6159147 ]
 [ 1.043